ALTER TABLE monitoring_result_rows
    ADD COLUMN row_status  VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN row_comment TEXT        NULL,
    ADD COLUMN updated_at  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
