apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.common.appDetail.name }}
  {{- if or (eq .Values.common.appDetail.branch "develop") (eq .Values.common.appDetail.branch "release") }}
  namespace: {{ .Values.common.appDetail.nameSpace }}
  {{- else }}
  namespace: {{ .Values.common.appDetail.nameSpaceEnv }}
  {{- end }}
type: Opaque
data:
  JAVA_OPTS: {{ "ENV_JAVA_OPTS" | b64enc }}
  DB_HOST: {{ "ENV_DB_HOST" | b64enc }}
  DB_USER: {{ "ENV_DB_USER" | b64enc }}
  DB_PASSWORD: {{ "ENV_DB_PASSWORD" | b64enc }}
  DB1_HOST: {{ "ENV_DB1_HOST" | b64enc }}
  DB1_USER: {{ "ENV_DB1_USER" | b64enc }}
  DB1_PASSWORD: {{ "ENV_DB1_PASSWORD" | b64enc }}
  DB1_NAME: {{ "ENV_DB1_NAME" | b64enc }}
  DB2_HOST: {{ "ENV_DB2_HOST" | b64enc }}
  DB2_USER: {{ "ENV_DB2_USER" | b64enc }}
  DB2_PASSWORD: {{ "ENV_DB2_PASSWORD" | b64enc }}
  DB2_NAME: {{ "ENV_DB2_NAME" | b64enc }}
  DB3_HOST: {{ "ENV_DB3_HOST" | b64enc }}
  DB3_USER: {{ "ENV_DB3_USER" | b64enc }}
  DB3_PASSWORD: {{ "ENV_DB3_PASSWORD" | b64enc }}
  DB3_NAME: {{ "ENV_DB3_NAME" | b64enc }}
  # SENDGRID_ENABLED: {{ "true" | b64enc }}
  # SENDGRID_API_KEY: {{ "ENV_SENDGRID_API_KEY" | b64enc }}
  # SLACK_WEBHOOK_URL: {{ "ENV_SLACK_WEBHOOK_URL" | b64enc }}
